#pragma once

#define IDB_INDICATOR_UD                        "Bitmaps/DeltaGliderXR1/IndicatorUD.bmp"
#define IDB_INDICATOR_AV                        "Bitmaps/DeltaGliderXR1/IndicatorAV.bmp"
#define IDB_INDICATOR_SD                        "Bitmaps/DeltaGliderXR1/IndicatorSD.bmp"
#define IDB_RED_INDICATOR2                      "Bitmaps/DeltaGliderXR1/RedIndicator2.bmp"
#define IDB_YELLOW_INDICATOR2                   "Bitmaps/DeltaGliderXR1/YellowIndicator2.bmp"
#define IDB_GREEN_INDICATOR2                    "Bitmaps/DeltaGliderXR1/GreenIndicator2.bmp"
#define IDB_FONT2_RED                           "Bitmaps/DeltaGliderXR1/font2_red.bmp"
#define IDB_FONT2_YELLOW                        "Bitmaps/DeltaGliderXR1/font2_yellow.bmp"
#define IDB_GSCALE                              "Bitmaps/DeltaGliderXR1/G Scale.bmp"
#define IDB_HULL_TEMP_MULTI_DISPLAY             "Bitmaps/DeltaGliderXR1/HullTempMultiDisplay.bmp"
#define IDB_BLUE_INDICATOR2                     "Bitmaps/DeltaGliderXR1/BlueIndicator2.bmp"
#define IDB_MDM_BUTTON                          "Bitmaps/DeltaGliderXR1/MDMButton.bmp"
#define IDB_SYSTEMS_STATUS2_MULTI_DISPLAY       "Bitmaps/DeltaGliderXR1/Systems Status Display #2.bmp"
#define IDB_SYSTEMS_STATUS1_MULTI_DISPLAY       "Bitmaps/DeltaGliderXR1/Systems Status Display #1.bmp"
#define IDB_SYSTEMS_STATUS4_MULTI_DISPLAY       "Bitmaps/DeltaGliderXR1/Systems Status Display #4.bmp"
#define IDB_SYSTEMS_STATUS3_MULTI_DISPLAY       "Bitmaps/DeltaGliderXR1/Systems Status Display #3.bmp"
#define IDB_SYSTEMS_STATUS5_MULTI_DISPLAY       "Bitmaps/DeltaGliderXR1/Systems Status Display #5.bmp"
#define IDB_WARNING_LIGHTS                      "Bitmaps/DeltaGliderXR1/Warning Lights.bmp"
#define IDB_APU_BUTTON                          "Bitmaps/DeltaGliderXR1/APU Button.bmp"
#define IDB_FUEL_GAUGE                          "Bitmaps/DeltaGliderXR1/fuelGauge.bmp"
#define IDB_DIAL2                               "Bitmaps/DeltaGliderXR1/Dial2.bmp"
#define IDB_GREEN_LED_SMALL                     "Bitmaps/DeltaGliderXR1/GreenLED small.bmp"
#define IDB_LOX_GAUGE                           "Bitmaps/DeltaGliderXR1/LOX Gauge.bmp"
#define IDB_FONT2_BLUE                          "Bitmaps/DeltaGliderXR1/font2_blue.bmp"
#define IDB_COOLANT_GAUGE                       "Bitmaps/DeltaGliderXR1/coolant Gauge.bmp"
#define IDB_GREEN_LED_TINY                      "Bitmaps/DeltaGliderXR1/greenled tiny.bmp"
#define IDB_ATTITUDE_HOLD_MULTI_DISPLAY         "Bitmaps/DeltaGliderXR1/AttitudeHoldMultiDisplay.bmp"
#define IDB_DESCENT_HOLD_MULTI_DISPLAY          "Bitmaps/DeltaGliderXR1/DescentHoldMultiDisplay.bmp"
#define IDB_AIRSPEED_HOLD_MULTI_DISPLAY         "Bitmaps/DeltaGliderXR1/AirspeedHoldMultiDisplay.bmp"
#define IDB_FONT2_WHITE                         "Bitmaps/DeltaGliderXR1/font2_white.bmp"
#define IDB_INDICATOR4                          "Bitmaps/DeltaGliderXR1/Indicator4.bmp"
#define IDB_INDICATOR4_YELLOW                   "Bitmaps/DeltaGliderXR1/indicator4 Yellow.bmp"
#define IDB_DIAL1                               "Bitmaps/DeltaGliderXR1/Dial1.bmp"
#define IDB_NAVBUTTON                           "Bitmaps/DeltaGliderXR1/Navbutton.bmp"
#define IDB_SWITCH1                             "Bitmaps/DeltaGliderXR1/Switch1.bmp"
#define IDB_LIGHT1                              "Bitmaps/DeltaGliderXR1/Light1.bmp"
#define IDB_HORIZON                             "Bitmaps/DeltaGliderXR1/Horizon.bmp"
#define IDB_SLIDER1                             "Bitmaps/DeltaGliderXR1/Slider1.bmp"
#define IDB_VPITCH                              "Bitmaps/DeltaGliderXR1/Vpitch.bmp"
#define IDB_VBANK                               "Bitmaps/DeltaGliderXR1/Vbank.bmp"
#define IDB_VYAW                                "Bitmaps/DeltaGliderXR1/Vyaw.bmp"
#define IDB_SWITCH4                             "Bitmaps/DeltaGliderXR1/Switch4.bmp"
#define IDB_INDICATOR2                          "Bitmaps/DeltaGliderXR1/Indicator2.bmp"
#define IDB_SWITCH4R                            "Bitmaps/DeltaGliderXR1/Switch4r.bmp"
#define IDB_LIGHT2                              "Bitmaps/DeltaGliderXR1/Light2.bmp"
#define IDB_COVER1                              "Bitmaps/DeltaGliderXR1/Cover1.bmp"
#define IDB_COVER2                              "Bitmaps/DeltaGliderXR1/Cover2.bmp"
#define IDB_FONT2                               "Bitmaps/DeltaGliderXR1/font2.bmp"
#define IDB_WARN                                "Bitmaps/DeltaGliderXR1/warn.bmp"
#define IDB_SWITCH3                             "Bitmaps/DeltaGliderXR1/Switch3.bmp"
#define IDB_INDICATOR_OC                        "Bitmaps/DeltaGliderXR1/IndicatorOC.bmp"
#define IDB_PANEL1_1600                         "Bitmaps/DeltaGliderXR1/panel1-1600.bmp"
#define IDB_PANEL2_1600                         "Bitmaps/DeltaGliderXR1/panel2-1600.bmp"
#define IDB_PANEL3_1600                         "Bitmaps/DeltaGliderXR1/panel3-1600.bmp"
#define IDB_PANEL1_1920                         "Bitmaps/DeltaGliderXR1/panel1-1920.bmp"
#define IDB_PANEL2_1920                         "Bitmaps/DeltaGliderXR1/panel2-1920.bmp"
#define IDB_PANEL3_1920                         "Bitmaps/DeltaGliderXR1/panel3-1920.bmp"
#define IDB_PANEL3_1280                         "Bitmaps/DeltaGliderXR1/Panel3-1280.bmp"
#define IDB_PANEL1_1280                         "Bitmaps/DeltaGliderXR1/panel1-1280.bmp"
#define IDB_PANEL2_1280                         "Bitmaps/DeltaGliderXR1/panel2-1280.bmp"
#define IDB_REENTRY_CHECK_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/ReentryCheck Display.bmp"
