#pragma once

#define IDB_REENTRY_CHECK_MULTI_DISPLAY         "Bitmaps/XR2Ravenstar/ReentryCheck Display.bmp"
#define IDB_PANEL1_1600                         "Bitmaps/XR2Ravenstar/Panel1-1600.bmp"
#define IDB_PANEL2_1600                         "Bitmaps/XR2Ravenstar/PANEL2-1600.bmp"
#define IDB_PANEL3_1600                         "Bitmaps/XR2Ravenstar/PANEL3-1600.bmp"
#define IDB_PANEL1_1920                         "Bitmaps/XR2Ravenstar/panel1-1920.bmp"
#define IDB_PANEL2_1920                         "Bitmaps/XR2Ravenstar/panel2-1920.bmp"
#define IDB_PANEL3_1920                         "Bitmaps/XR2Ravenstar/panel3-1920.bmp"
#define IDB_PANEL4_1280                         "Bitmaps/XR2Ravenstar/panel4-1280.bmp"
#define IDB_PANEL4_1600                         "Bitmaps/XR2Ravenstar/panel4-1600.bmp"
#define IDB_PANEL4_1920                         "Bitmaps/XR2Ravenstar/panel4-1920.bmp"
#define IDB_XR2_WARNING_LIGHTS                  "Bitmaps/XR2Ravenstar/XR2 Warning Lights.bmp"
#define IDB_SELECT_BAY_SLOT                     "Bitmaps/XR2Ravenstar/SelectBaySlot.bmp"
#define IDB_DEPLOY_PAYLOAD_ORBIT                "Bitmaps/XR2Ravenstar/DeployPayloadOrbit.bmp"
#define IDB_DEPLOY_PAYLOAD_LANDED               "Bitmaps/XR2Ravenstar/DeployPayloadLanded.bmp"
#define IDB_PAYLOAD_THUMBNAIL_NONE              "Bitmaps/XR2Ravenstar/PayloadThumbnailNone.bmp"
#define IDB_GRAPPLE_PAYLOAD                     "Bitmaps/XR2Ravenstar/grapplePayload.bmp"
#define IDB_FUEL_GAUGE_DARK                     "Bitmaps/XR2Ravenstar/FuelGaugeDark.bmp"
#define IDB_LOX_GAUGE_DARK                      "Bitmaps/XR2Ravenstar/LOX Gauge Dark.bmp"
#define IDB_PANEL2_1280                         "Bitmaps/XR2Ravenstar/Panel2-1280.bmp"
#define IDB_PANEL3_1280                         "Bitmaps/XR2Ravenstar/Panel3-1280.bmp"
#define IDB_PANEL1_1280                         "Bitmaps/XR2Ravenstar/Panel1-1280.bmp"
#define IDB_VPITCH                              "Bitmaps/DeltaGliderXR1/Vpitch.bmp"
#define IDB_VBANK                               "Bitmaps/DeltaGliderXR1/Vbank.bmp"
#define IDB_VYAW                                "Bitmaps/DeltaGliderXR1/Vyaw.bmp"
#define IDB_LIGHT2                              "Bitmaps/DeltaGliderXR1/Light2.bmp"
#define IDB_INDICATOR2                          "Bitmaps/DeltaGliderXR1/Indicator2.bmp"
#define IDB_RED_INDICATOR2                      "Bitmaps/DeltaGliderXR1/RedIndicator2.bmp"
#define IDB_YELLOW_INDICATOR2                   "Bitmaps/DeltaGliderXR1/YellowIndicator2.bmp"
#define IDB_GREEN_INDICATOR2                    "Bitmaps/DeltaGliderXR1/GreenIndicator2.bmp"
#define IDB_GSCALE                              "Bitmaps/DeltaGliderXR1/G Scale.bmp"
#define IDB_GREEN_LED_SMALL                     "Bitmaps/DeltaGliderXR1/GreenLED small.bmp"
#define IDB_FONT2                               "Bitmaps/DeltaGliderXR1/font2.bmp"
#define IDB_FONT2_YELLOW                        "Bitmaps/DeltaGliderXR1/font2_yellow.bmp"
#define IDB_FONT2_RED                           "Bitmaps/DeltaGliderXR1/font2_red.bmp"
#define IDB_FONT2_BLUE                          "Bitmaps/DeltaGliderXR1/font2_blue.bmp"
#define IDB_FONT2_WHITE                         "Bitmaps/DeltaGliderXR1/font2_white.bmp"
#define IDB_SWITCH4                             "Bitmaps/DeltaGliderXR1/Switch4.bmp"
#define IDB_SWITCH4R                            "Bitmaps/DeltaGliderXR1/Switch4r.bmp"
#define IDB_SWITCH1                             "Bitmaps/DeltaGliderXR1/Switch1.bmp"
#define IDB_DIAL1                               "Bitmaps/DeltaGliderXR1/Dial1.bmp"
#define IDB_INDICATOR_SD                        "Bitmaps/DeltaGliderXR1/IndicatorSD.bmp"
#define IDB_INDICATOR_OC                        "Bitmaps/DeltaGliderXR1/IndicatorOC.bmp"
#define IDB_INDICATOR_AV                        "Bitmaps/DeltaGliderXR1/IndicatorAV.bmp"
#define IDB_INDICATOR_UD                        "Bitmaps/DeltaGliderXR1/IndicatorUD.bmp"
#define IDB_DESCENT_HOLD_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/DescentHoldMultiDisplay.bmp"
#define IDB_HULL_TEMP_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/HullTempMultiDisplay.bmp"
#define IDB_GREEN_LED_TINY                      "Bitmaps/DeltaGliderXR1/greenled tiny.bmp"
#define IDB_WARN                                "Bitmaps/DeltaGliderXR1/warn.bmp"
#define IDB_WARNING_LIGHTS                      "Bitmaps/XR2Ravenstar/Warning Lights.bmp"
#define IDB_NAVBUTTON                           "Bitmaps/DeltaGliderXR1/Navbutton.bmp"
#define IDB_APU_BUTTON                          "Bitmaps/DeltaGliderXR1/APU Button.bmp"
#define IDB_LIGHT1                              "Bitmaps/DeltaGliderXR1/Light1.bmp"
#define IDB_INDICATOR4                          "Bitmaps/DeltaGliderXR1/Indicator4.bmp"
#define IDB_INDICATOR4_YELLOW                   "Bitmaps/DeltaGliderXR1/indicator4 Yellow.bmp"
#define IDB_SLIDER1                             "Bitmaps/DeltaGliderXR1/Slider1.bmp"
#define IDB_SYSTEMS_STATUS2_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/Systems Status Display #2.bmp"
#define IDB_SYSTEMS_STATUS1_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/Systems Status Display #1.bmp"
#define IDB_SYSTEMS_STATUS4_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/Systems Status Display #4.bmp"
#define IDB_SYSTEMS_STATUS3_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/Systems Status Display #3.bmp"
#define IDB_SYSTEMS_STATUS5_MULTI_DISPLAY                 "Bitmaps/DeltaGliderXR1/Systems Status Display #5.bmp"
#define IDB_COOLANT_GAUGE                       "Bitmaps/DeltaGliderXR1/coolant Gauge.bmp"
#define IDB_LOX_GAUGE                           "Bitmaps/DeltaGliderXR1/LOX Gauge.bmp"
#define IDB_FUEL_GAUGE                          "Bitmaps/DeltaGliderXR1/fuelGauge.bmp"
